### ISSUE TITLE
Investigate dependencies improvement

### ISSUE THREAD

**Issue by helio-frota** [nodeshift-starters/nodejs-messaging-work-queue#54]
from @pacostas :

```
we can remove all the dependencies except the rhea and kube-service-bindings packages. We can leave devDependencies as is. That way we can reduce lots of snyk PRs.

Also move the devDependencies one directory up, that way we cut the snyk PRs for dev dependencies in to half.
```

**Comment by pacostas** [comment]
I have a similar example for mongodb https://github.com/nodeshift-blog-examples/kube-service-bindings-examples/tree/main/src/mongodb  and here is the top level with devDependencies https://github.com/nodeshift-blog-examples/kube-service-bindings-examples . So if you click on npm install on the mongodb, will also install the eslint which is on the top level

**Comment by helio-frota** [comment]
hey @pacostas feel free to close this and create a new one with more elaborated description etc :+1:

**Comment by helio-frota** [comment]
hi @pacostas I'm going to close this issue, feel free to create a new one if needed :+1:
